spring:
  application:
    name: hfriedri-demo
  profiles:
    active: default

server:
  port: 9090
  
info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
  enabled: true
  git:
    mode: full
    
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,info
      path-mapping:
        health: internal /health
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
  health:
    mongo:
      enabled: false
    diskSpace:
      enabled: false
