###
# #%L
# Project: hfriedri-demo
# File: classdiagramm-sample.puml
# %%
# Copyright (C) 2021 Hfriedri
# %%
# Header of my_license
# #L%
###
@startuml

abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
  Object[] elementData
  size()
}

enum TimeUnit {
  DAYS
  HOURS
  MINUTES
}

annotation SuppressWarnings

@enduml
